In [ ]:
from keras.datasets.cifar10 import load_data

In [ ]:
(x_train, y_train), (x_test, y_test)  = load_data()

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x_train.shape

(50000, 32, 32, 3)

In [ ]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [ ]:
from keras.layers import Conv2D,MaxPooling2D,Flatten,Dense,BatchNormalization
from keras.models import Sequential

In [ ]:
model = Sequential()
model.add(Conv2D(32,(2,2),activation="relu",input_shape=(32,32,3)))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(128,(2,2),activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(2,2),activation="relu"))
model.add(BatchNormalization())

model.add(Flatten())
model.add(Dense(64,activation="relu"))
model.add(Dense(10,activation="softmax"))

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [ ]:
model.fit(x_train,y_train,epochs=20,batch_size=5000)

Epoch 1/20
10/10 [==============================] - 3s 349ms/step - loss: 2.0034 - accuracy: 0.3125
Epoch 2/20
10/10 [==============================] - 3s 341ms/step - loss: 1.4392 - accuracy: 0.4906
Epoch 3/20
10/10 [==============================] - 3s 344ms/step - loss: 1.2372 - accuracy: 0.5646
Epoch 4/20
10/10 [==============================] - 3s 341ms/step - loss: 1.1028 - accuracy: 0.6120
Epoch 5/20
10/10 [==============================] - 3s 343ms/step - loss: 0.9972 - accuracy: 0.6507
Epoch 6/20
10/10 [==============================] - 3s 344ms/step - loss: 0.9088 - accuracy: 0.6833
Epoch 7/20
10/10 [==============================] - 3s 344ms/step - loss: 0.8352 - accuracy: 0.7122
Epoch 8/20
10/10 [==============================] - 3s 343ms/step - loss: 0.7698 - accuracy: 0.7371
Epoch 9/20
10/10 [==============================] - 3s 340ms/step - loss: 0.7163 - accuracy: 0.7554
Epoch 10/20
10/10 [==============================] - 3s 342ms/step - loss: 0.6640 - accuracy: 0.7743

In [ ]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 4ms/step - loss: 1.1107 - accuracy: 0.6283


[1.1107467412948608, 0.6283000111579895]

In [ ]:
model.predict(x_test)[0]

array([0.07387665, 0.00421421, 0.03517856, 0.30396578, 0.07631193,
       0.17538817, 0.23665695, 0.01126927, 0.08163593, 0.00150257],
      dtype=float32)

In [ ]:
from PIL import Image
import numpy as np

In [ ]:
im = np.array(Image.open('/content/dog (1).jpg'))

In [ ]:
np.argmax(model.predict(im.reshape(1,32,32,3)))

5

In [ ]:
model.predict(im.reshape(1,32,32,3))

array([[0.07685161, 0.00602691, 0.00722714, 0.22981155, 0.21476962,
        0.23423499, 0.02331303, 0.0856337 , 0.11099745, 0.01113406]],
      dtype=float32)

In [ ]:
model.save()